### ISSUE TITLE
Your gif in the vscode gallery goes too fast

### ISSUE THREAD

**Issue by jzabroski** [andersfibiger/csharper#2]
Nobody can really read what the thing is doing it goes too fast.  Use half or quarter speed.

**Comment by andersfibiger** [comment]
Hey! 

I could slow it down or have some more time in the end of the gif, so you can see the mocked dependencies?

**Comment by jzabroski** [comment]
Yes, both approaches combined would be ideal.

**Comment by andersfibiger** [comment]
Super, I have updated the README for now :)
